apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: aks-nvme-ssd-provisioner
  labels:
    app: aks-nvme-ssd-provisioner
spec:
  selector:
    matchLabels:
      name: aks-nvme-ssd-provisioner
  template:
    metadata:
      labels:
        name: aks-nvme-ssd-provisioner
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.azure.com/aks-local-ssd: "true"
      priorityClassName: system-node-critical
      containers:
        - name: aks-nvme-ssd-provisioner
          image: ams0/aks-nvme-ssd-provisioner:v1.0.0
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /pv-disks
              name: pv-disks
              mountPropagation: "Bidirectional"
      volumes:
        - name: pv-disks
          hostPath:
            path: /pv-disks
